#i2c addresses
# address: 0x26 input pcf io
# address: 0x27 input pcf io
# address: 0x3C input oled
# address: 0x40 input ina219 power
# address: 0x68 input rtc ds1307

binary_sensor:
  - platform: gpio
    name: "${node_name} IN_01 salon wejscie 01"
    id: in_01
    pin:
      pcf8574: pcf_inputs_1to14
      number: 0
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_11

  - platform: gpio
    name: "${node_name} IN_02 salon wejscie-02"
    id: in_02
    pin:
      pcf8574: pcf_inputs_1to14
      number: 1
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_12

  - platform: gpio
    name: "${node_name} IN_03 salon wejscie-03"
    id: in_03
    pin:
      pcf8574: pcf_inputs_1to14
      number: 2
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_13

  - platform: gpio
    name: "${node_name} IN_04 salon wejscie-03"
    id: in_04
    pin:
      pcf8574: pcf_inputs_1to14
      number: 3
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_14

  - platform: gpio
    name: "${node_name} IN_05 salon wejscie-05"
    id: in_05
    pin:
      pcf8574: pcf_inputs_1to14
      number: 4
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_16

  - platform: gpio
    name: "${node_name} IN_06 salon wejscie-06"
    id: in_06
    pin:
      pcf8574: pcf_inputs_1to14
      number: 5
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_15

  - platform: gpio
    name: "${node_name} IN_07 salon wejscie-07"
    id: in_07
    pin:
      pcf8574: pcf_inputs_1to14
      number: 6
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_19

  - platform: gpio
    name: "${node_name} IN_08 salon wejscie-08"
    id: in_08
    pin:
      pcf8574: pcf_inputs_1to14
      number: 8
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_17

  - platform: gpio
    name: "${node_name} IN_09 jadalnia balkon 01"
    id: in_09
    pin:
      pcf8574: pcf_inputs_1to14
      number: 9
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_16

  - platform: gpio
    name: "${node_name} IN_10 jadalnia balkon 02"
    id: in_10
    pin:
      pcf8574: pcf_inputs_1to14
      number: 10
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_15

  - platform: gpio
    name: "${node_name} IN_11 salon kanapa 01"
    id: in_11
    pin:
      pcf8574: pcf_inputs_1to14
      number: 11
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_11

  - platform: gpio
    name: "${node_name} IN_12 salon kanapa 02"
    id: in_12
    pin:
      pcf8574: pcf_inputs_1to14
      number: 12
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_12

  - platform: gpio
    name: "${node_name} IN_13 salon kanapa 03"
    id: in_13
    pin:
      pcf8574: pcf_inputs_1to14
      number: 13
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_13

  - platform: gpio
    name: "${node_name} IN_14 salon kanapa 04"
    id: in_14
    pin:
      pcf8574: pcf_inputs_1to14
      number: 14
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_14

  - platform: gpio
    name: "${node_name} IN_15 kuchnia blat 01"
    id: in_15
    pin:
      pcf8574: pcf_inputs_15to28
      number: 6
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_19

  - platform: gpio
    name: "${node_name} IN_16 kuchnia blat 02"
    id: in_16
    pin:
      pcf8574: pcf_inputs_15to28
      number: 5
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_17

  - platform: gpio
    name: "${node_name} IN_17 lazienka wew 01"
    id: in_17
    pin:
      pcf8574: pcf_inputs_15to28
      number: 4
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_1

  - platform: gpio
    name: "${node_name} IN_18 lazienka wew 02"
    id: in_18
    pin:
      pcf8574: pcf_inputs_15to28
      number: 3
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_2

  - platform: gpio
    name: "${node_name} IN_19 pokoj dol 01"
    id: in_19
    pin:
      pcf8574: pcf_inputs_15to28
      number: 2
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_5

  - platform: gpio
    name: "${node_name} IN_20 pokoj dol 02"
    id: in_20
    pin:
      pcf8574: pcf_inputs_15to28
      number: 1
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_6

  - platform: gpio
    name: "${node_name} IN_21 kotlownia 01"
    id: in_21
    pin:
      pcf8574: pcf_inputs_15to28
      number: 0
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_23

  - platform: gpio
    name: "${node_name} IN_22 kotlownia 02"
    id: in_22
    pin:
      pcf8574: pcf_inputs_15to28
      number: 8
      mode:
        input: true
      inverted: true
    # on_press:
    #   then:
    #     - switch.toggle: relay_22

  - platform: gpio
    name: "${node_name} IN_23 garaz - kotlownia 01"
    id: in_23
    pin:
      pcf8574: pcf_inputs_15to28
      number: 9
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_21

  - platform: gpio
    name: "${node_name} IN_24 garaz - kotlownia 02"
    id: in_24
    pin:
      pcf8574: pcf_inputs_15to28
      number: 10
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_22

  - platform: gpio
    name: "${node_name} IN_25 garaz - wiatrolap 02"
    id: in_25
    pin:
      pcf8574: pcf_inputs_15to28
      number: 11
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_21

  - platform: gpio
    name: "${node_name} IN_26 garaz - wiatrolap 02"
    id: in_26
    pin:
      pcf8574: pcf_inputs_15to28
      number: 12
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_22

  - platform: gpio
    name: "${node_name} IN_27"
    id: in_27
    pin:
      pcf8574: pcf_inputs_15to28
      number: 13
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_27

  - platform: gpio
    name: "${node_name} IN_28 Spizarka schody"
    id: in_28
    pin:
      pcf8574: pcf_inputs_15to28
      number: 14
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_9

  - platform: gpio
    name: "${node_name} IN_29 wiatrolap 01"
    id: in_29
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 0
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_7

  - platform: gpio
    name: "${node_name} IN_30 wiatrolap 02"
    id: in_30
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 1
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_8

  - platform: gpio
    name: "${node_name} IN_31 Spizarka kuchnia"
    id: in_31
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 2
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_10

  - platform: gpio
    name: "${node_name} IN_32 Kuchnia 03"
    id: in_32
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 3
      mode:
        input: true
      inverted: true
    # on_press:
    #   then:
    #     - switch.toggle: relay_32

  - platform: gpio
    name: "${node_name} IN_33 Kuchnia 04"
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 4
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_18
      
  - platform: gpio
    name: "${node_name} IN_34 lazienka zew 01"
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 5
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_3
      
  - platform: gpio
    name: "${node_name} IN_35 lazienka zew 02"
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 6
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_1

